server:
  port: 8081

logging:
  level:
    com.mytlx.handcraft: DEBUG

handcraft:
  rpc:
    server:
      port: 12345
      worker: 3
      backlog: 128
      host: 127.0.0.1
    client:
      worker: 3